spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PWD:postgres}
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update schema based on entities
    show-sql: true       # Log SQL statements
    properties:
      hibernate:
        format_sql: true  # Pretty print SQL